"""PostgreSQL persistence boundary for the Veetee control plane."""

from .conversation import (
    ConversationRepository,
    StoredConversation,
    StoredTurn,
    TurnInput,
    purge_expired_conversations,
)
from .correction import (
    ContextProviderConfigRepository,
    CorrectionRepository,
    StoredContextProviderConfig,
    StoredCorrectionRule,
    StoredCorrectionSet,
)
from .database import DatabaseConfig, PostgresDatabase
from .knowledge import (
    KnowledgeRepository,
    SearchResult,
    StoredChunk,
    StoredDataset,
    StoredDocument,
)
from .lifecycle import (
    AgentLifecycleRepository,
    StoredAgentSnapshot,
    StoredAgentTemplate,
    StoredTag,
)
from .repository import (
    ActivationRepository,
    Actor,
    AgentRepository,
    DeviceRepository,
    FirmwareReleaseRepository,
    ProviderRepository,
    StoredActivation,
    StoredAgent,
    StoredDevice,
    StoredFirmwareRelease,
    StoredProvider,
    UserRepository,
    hash_login_identifier,
    parse_semver,
    record_audit,
)
from .tooling import (
    StoredExternalEndpoint,
    StoredIntegrationPermission,
    ToolingRepository,
    validate_external_endpoint_url,
)

__all__ = [
    "ActivationRepository",
    "Actor",
    "AgentLifecycleRepository",
    "AgentRepository",
    "ContextProviderConfigRepository",
    "ConversationRepository",
    "CorrectionRepository",
    "DatabaseConfig",
    "DeviceRepository",
    "FirmwareReleaseRepository",
    "KnowledgeRepository",
    "PostgresDatabase",
    "ProviderRepository",
    "SearchResult",
    "StoredActivation",
    "StoredAgent",
    "StoredAgentSnapshot",
    "StoredAgentTemplate",
    "StoredChunk",
    "StoredContextProviderConfig",
    "StoredConversation",
    "StoredCorrectionRule",
    "StoredCorrectionSet",
    "StoredDataset",
    "StoredDevice",
    "StoredDocument",
    "StoredExternalEndpoint",
    "StoredFirmwareRelease",
    "StoredIntegrationPermission",
    "StoredProvider",
    "StoredTag",
    "StoredTurn",
    "ToolingRepository",
    "TurnInput",
    "UserRepository",
    "hash_login_identifier",
    "parse_semver",
    "purge_expired_conversations",
    "record_audit",
    "validate_external_endpoint_url",
]
