"""LLM providers and streaming pipeline contracts."""

from __future__ import annotations

from .contract import (
    ChatMessage,
    CompletedToolCall,
    LLMCancelledEvent,
    LLMCompletedEvent,
    LLMFailedEvent,
    LLMProvider,
    LLMResult,
    LLMStartedEvent,
    LLMStreamEvent,
    LLMTextDeltaEvent,
    LLMToolCallDeltaEvent,
    LLMUsage,
    LLMUsageEvent,
    OmniRouteLLMConfig,
    TextDelta,
    ToolCallDelta,
)
from .errors import (
    LLMAdmissionTimeoutError,
    LLMBusyError,
    LLMCircuitOpenError,
    LLMConnectTimeoutError,
    LLMEmptyResponseError,
    LLMError,
    LLMFirstTokenTimeoutError,
    LLMMalformedStreamError,
    LLMNotReadyError,
    LLMOversizedStreamError,
    LLMProviderAuthError,
    LLMProviderError,
    LLMProviderRateLimitError,
    LLMProviderUnavailableError,
    LLMTimeoutError,
    LLMTotalTimeoutError,
)
from .fake import FakeLLM
from .omniroute import CircuitBreaker, CircuitState, OmniRouteLLMAdapter, OmniRouteLLMRuntime

__all__ = [
    "ChatMessage",
    "CircuitBreaker",
    "CircuitState",
    "CompletedToolCall",
    "FakeLLM",
    "LLMAdmissionTimeoutError",
    "LLMBusyError",
    "LLMCancelledEvent",
    "LLMCircuitOpenError",
    "LLMCompletedEvent",
    "LLMConnectTimeoutError",
    "LLMEmptyResponseError",
    "LLMError",
    "LLMFailedEvent",
    "LLMFirstTokenTimeoutError",
    "LLMMalformedStreamError",
    "LLMNotReadyError",
    "LLMOversizedStreamError",
    "LLMProvider",
    "LLMProviderAuthError",
    "LLMProviderError",
    "LLMProviderRateLimitError",
    "LLMProviderUnavailableError",
    "LLMResult",
    "LLMStartedEvent",
    "LLMStreamEvent",
    "LLMTextDeltaEvent",
    "LLMToolCallDeltaEvent",
    "LLMTotalTimeoutError",
    "LLMTimeoutError",
    "LLMUsage",
    "LLMUsageEvent",
    "OmniRouteLLMAdapter",
    "OmniRouteLLMConfig",
    "OmniRouteLLMRuntime",
    "TextDelta",
    "ToolCallDelta",
]
