"""Memory domain model definitions, kinds, tenant scope, and proposals."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class MemoryKind(StrEnum):
    """Supported memory classifications."""

    WORKING = "working"
    EPISODIC = "episodic"
    PROFILE = "profile"


@dataclass(frozen=True, slots=True)
class TenantScope:
    """Strict tenant scope binding user and agent identities."""

    user_id: str
    agent_id: str


@dataclass(frozen=True, slots=True)
class Provenance:
    """Memory provenance tracking source session, turn, or directive."""

    source_type: str  # "user_explicit", "dialogue_turn", "system_generated"
    session_id: str = ""
    turn_id: str = ""
    description: str = ""

    def to_string(self) -> str:
        if self.session_id and self.turn_id:
            return f"{self.source_type}:{self.session_id}:{self.turn_id}"
        return f"{self.source_type}:{self.description or 'unspecified'}"


@dataclass(frozen=True, slots=True)
class MemoryEntry:
    """Typed memory record with provenance, confidence, and timestamp."""

    id: str
    tenant_scope: TenantScope
    kind: MemoryKind
    content: str
    provenance: str
    confidence: float = 1.0  # Range 0.0 - 1.0
    created_at: float = field(default_factory=lambda: time.time())
    updated_at: float = field(default_factory=lambda: time.time())
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(
                "Memory confidence must be between 0.0 and 1.0, "
                f"got {self.confidence}"
            )


@dataclass(frozen=True, slots=True)
class MemoryProposal:
    """Write proposal generated by model/assistant to be validated by memory policy."""

    content: str
    kind: MemoryKind
    tenant_scope: TenantScope
    provenance: str
    confidence: float = 0.8
    metadata: dict[str, Any] = field(default_factory=dict)
