"""Veetee Audio primitives module."""

from .codec import (
    DOWNLINK_PCM_FORMAT,
    UPLINK_PCM_FORMAT,
    AudioDecoder,
    AudioEncoder,
    AudioResampler,
    CodecError,
    DeferredNativeAudioDecoder,
    DeferredNativeAudioEncoder,
    DeferredNativeAudioResampler,
    DeferredNativeCodecError,
    DeferredNativeResamplerError,
    FakeOpusDecoder,
    FakeOpusEncoder,
    InvalidPCMFormatError,
    PCMFormat,
    build_opus_decoder,
    build_opus_encoder,
)
from .native_opus import NativeOpusDecoder, NativeOpusEncoder, is_native_opus_available
from .pacer import PacerError, PacerMetrics, PacketPacer
from .protocol import (
    AudioError,
    AudioPacketMetadata,
    AudioProtocolError,
    MalformedAudioFrameError,
    OversizedAudioFrameError,
    ProtocolVersionMismatchError,
    encode_audio_frame,
    parse_audio_frame,
)
from .queue import (
    AudioQueueItem,
    BoundedAudioQueue,
    OverflowPolicy,
    QueueClosedError,
    QueueError,
    QueueOverflowError,
    SlowClientQueueOverflowError,
)

__all__ = [
    "DOWNLINK_PCM_FORMAT",
    "UPLINK_PCM_FORMAT",
    "AudioDecoder",
    "AudioEncoder",
    "AudioError",
    "AudioPacketMetadata",
    "AudioProtocolError",
    "AudioQueueItem",
    "AudioResampler",
    "BoundedAudioQueue",
    "CodecError",
    "DeferredNativeAudioDecoder",
    "DeferredNativeAudioEncoder",
    "DeferredNativeAudioResampler",
    "DeferredNativeCodecError",
    "DeferredNativeResamplerError",
    "FakeOpusDecoder",
    "FakeOpusEncoder",
    "InvalidPCMFormatError",
    "MalformedAudioFrameError",
    "NativeOpusDecoder",
    "NativeOpusEncoder",
    "OverflowPolicy",
    "OversizedAudioFrameError",
    "PCMFormat",
    "PacketPacer",
    "PacerError",
    "PacerMetrics",
    "ProtocolVersionMismatchError",
    "QueueClosedError",
    "QueueError",
    "QueueOverflowError",
    "SlowClientQueueOverflowError",
    "build_opus_decoder",
    "build_opus_encoder",
    "encode_audio_frame",
    "is_native_opus_available",
    "parse_audio_frame",
]
